use anyhow::Result;
use human_bytes::human_bytes;
use reqwest::multipart::{Form, Part};
use serde_json::json;
use std::path::Path;

use crate::bag_meta::ParsedBagSummary;

pub async fn send_to_discord(
    webhook_url: &str,
    bag_summary: &ParsedBagSummary,
    archive_path: Option<&Path>,
    raw_size_bytes: u64,
    compressed_size_bytes: Option<u64>,
    max_upload_size_mb: u64,
    custom_comment: Option<&str>,
) -> Result<()> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(120))
        .build()?;

    let (duration_formatted, topics_table, compression_info) = format_summary_details(
        bag_summary,
        raw_size_bytes,
        compressed_size_bytes,
    );

    let mut description = String::new();
    if let Some(comment) = custom_comment {
        description.push_str(&format!("**Note:** {}\n\n", comment));
    }
    description.push_str(&format!("**Bag Name:** `{}`\n", bag_summary.bag_name));
    description.push_str(&format!("**Storage:** `{}` | **Messages:** `{}`\n", bag_summary.storage_format, bag_summary.message_count));
    description.push_str(&format!("**Duration:** `{}` | **Start:** `{}`\n", duration_formatted, bag_summary.start_time_str));
    description.push_str(&format!("**Size:** {}\n\n", compression_info));
    description.push_str(&format!("**Topics ({})**\n```\n{}\n```", bag_summary.topics.len(), topics_table));

    let max_bytes = max_upload_size_mb * 1024 * 1024;
    let will_attach_file = if let Some(path) = archive_path {
        let size = path.metadata()?.len();
        size <= max_bytes
    } else {
        false
    };

    let embed_color = if will_attach_file { 0x57F287 } else { 0xFEE75C }; // Green if attached, Yellow if too big

    let embed = json!({
        "title": format!("📦 ROS 2 Bag Report: {}", bag_summary.bag_name),
        "description": description,
        "color": embed_color,
        "footer": {
            "text": "Generated by bagpipe (rosbag-pipe)"
        },
        "timestamp": chrono::Utc::now().to_rfc3339()
    });

    if will_attach_file {
        let path = archive_path.unwrap();
        let file_bytes = tokio::fs::read(path).await?;
        let filename = path.file_name().unwrap().to_string_lossy().to_string();

        let part = Part::bytes(file_bytes)
            .file_name(filename)
            .mime_str("application/octet-stream")?;

        let payload_json = json!({
            "embeds": [embed]
        });

        let form = Form::new()
            .text("payload_json", payload_json.to_string())
            .part("files[0]", part);

        let res = client.post(webhook_url).multipart(form).send().await?;
        if !res.status().is_success() {
            let status = res.status();
            let text = res.text().await.unwrap_or_default();
            anyhow::bail!("Discord API returned error {}: {}", status, text);
        }
    } else {
        let mut note = String::new();
        if let Some(path) = archive_path {
            let size = path.metadata()?.len();
            note = format!(
                "\n⚠️ **File not uploaded:** Compressed archive ({}) exceeds Discord limit ({}MB).\nArchive saved locally at: `{}`",
                human_bytes(size as f64),
                max_upload_size_mb,
                path.display()
            );
        }

        let mut embed_obj = embed;
        if let Some(desc) = embed_obj.get_mut("description").and_then(|d| d.as_str()) {
            let mut new_desc = desc.to_string();
            new_desc.push_str(&note);
            embed_obj["description"] = json!(new_desc);
        }

        let payload_json = json!({
            "embeds": [embed_obj]
        });

        let res = client.post(webhook_url).json(&payload_json).send().await?;
        if !res.status().is_success() {
            let status = res.status();
            let text = res.text().await.unwrap_or_default();
            anyhow::bail!("Discord API returned error {}: {}", status, text);
        }
    }

    Ok(())
}

fn format_summary_details(
    bag_summary: &ParsedBagSummary,
    raw_size_bytes: u64,
    compressed_size_bytes: Option<u64>,
) -> (String, String, String) {
    let dur_sec = bag_summary.duration_sec;
    let hours = (dur_sec / 3600.0) as u64;
    let mins = ((dur_sec % 3600.0) / 60.0) as u64;
    let secs = dur_sec % 60.0;
    let duration_formatted = if hours > 0 {
        format!("{}h {:02}m {:04.1}s", hours, mins, secs)
    } else if mins > 0 {
        format!("{}m {:04.1}s", mins, secs)
    } else {
        format!("{:.2}s", secs)
    };

    let compression_info = if let Some(comp) = compressed_size_bytes {
        let ratio = if raw_size_bytes > 0 {
            (comp as f64 / raw_size_bytes as f64) * 100.0
        } else {
            100.0
        };
        format!(
            "{} ➔ **{}** (zstd: {:.1}% of original)",
            human_bytes(raw_size_bytes as f64),
            human_bytes(comp as f64),
            ratio
        )
    } else {
        human_bytes(raw_size_bytes as f64)
    };

    let mut lines = Vec::new();
    let limit = 15;
    for (i, (name, type_name, count)) in bag_summary.topics.iter().enumerate() {
        if i >= limit {
            lines.push(format!("... and {} more topics", bag_summary.topics.len() - limit));
            break;
        }
        let short_type = type_name.split('/').last().unwrap_or(type_name);
        lines.push(format!("{:<30} {:<15} {:>6} msgs", truncate(name, 30), truncate(short_type, 15), count));
    }
    if lines.is_empty() {
        lines.push("No messages or topics recorded.".to_string());
    }

    (duration_formatted, lines.join("\n"), compression_info)
}

fn truncate(s: &str, max_chars: usize) -> String {
    if s.chars().count() > max_chars {
        let t: String = s.chars().take(max_chars.saturating_sub(2)).collect();
        format!("{}..", t)
    } else {
        s.to_string()
    }
}
